brew 'caskroom/cask/brew-cask'

#brew 'jpeg'
#brew 'libtiff'
#brew 'openexr'
#brew 'libpng'
#brew 'webp'
#brew 'go'
#brew 'ffmpeg'
brew 'jq'
brew 'tree'
brew 'tmux'
brew 'wget'
#brew 'heroku-toolbelt'
#brew 'emacs', args: ['use-git-head', 'cocoa', 'srgb']
#brew 'imagemagick', args: ['with-libtiff', 'with-openexr', 'with-webp']
#brew 'spark'
#brew 'mercurial'
#brew 'hub'
#brew 'bash-completion'
#brew 'docker'
#brew 'docker-compose'
#brew 'docker-machine'
#brew 'docker-swarm'
brew 'md5sha1sum'
brew 'bash-completion'
#brew 'spark'
#brew 'siege'
#brew 'hub'
brew 'node'


#tap 'homebrew/completions'
#brew 'docker-completion'
#brew 'docker-machine-completion'
#brew 'packer-completion'
#brew 'brew-cask-completion'

#cask 'google-chrome'
#cask 'alfred'
#cask 'dropbox'
#cask 'moom'
cask 'iterm2'
#cask 'flux'
#cask 'geektool'
#cask 'virtualbox'
#cask 'evernote'
#cask 'firefox'
#cask 'sublime-text'
#cask 'hipchat'
#cask 'limechat'
#cask 'skitch'
#cask 'google-hangouts'
#cask 'silverlight'
#cask 'firefox'
#cask 'evernote'
#cask 'gpgtools'
#cask 'kindle'
#cask 'steam'
#cask 'lastpass'
# cask 'xquartz'
#cask 'playonmac'
#cask 'battle-net'
#cask 'adobe-creative-cloud'
#cask 'atom'
#cask 'packer'
#cask 'postgres'
#cask 'mailbox'
#cask 'vagrant'
