#!/usr/bin/python
import os
import glob

from mow import task

ROOT = os.path.dirname(__file__)

def mklink(src, dest):
    if os.path.exists(dest):
        print "{0}: Already exists".format(dest)
    else:
        try:
            os.symlink(src, dest)
        except OSError, e:
            print "{0}: Already exists".format(dest)
            return
        print "Created link {0}".format(dest)


@task('install-emacs')
def emacs():
    """Install Emacs dot files"""
    emacs_dir = os.path.join(ROOT, 'emacs')
    emacs_link = os.path.expanduser('~/.emacs.d')
    mklink(emacs_dir, emacs_link)

@task('install-bash')
def bash():
    """Install Bash dot files"""
    bash_dir =  os.path.join(ROOT, 'bash')
    bashp_file = os.path.join(bash_dir, 'bash_profile.sh')
    bashp_link = os.path.expanduser('~/.bash_profile')
    mklink(bashp_file, bashp_link)

    bashrc_file = os.path.join(bash_dir, 'bashrc.sh')
    bashrc_link = os.path.expanduser('~/.bashrc')
    mklink(bashrc_file, bashrc_link)

@task('install-tcsh')
def tcsh():
    """Install Tcsh dot files"""
    tcsh_dir =  os.path.join(ROOT, 'tcsh')
    tcsh_file = os.path.join(tcsh_dir, 'tcshrc')
    tcsh_link = os.path.expanduser('~/.tcshrc')
    mklink(tcsh_file, tcsh_link)

@task('install-hg')
def hg():
    """Install Mercurial dot files"""
    hg_dir =  os.path.join(ROOT, 'hg')
    hgrc_file = os.path.join(hg_dir, 'hgrc')
    hgrc_link = os.path.expanduser('~/.hgrc')
    mklink(hgrc_file, hgrc_link)

    hgignore_file = os.path.join(hg_dir, 'hgignore')
    hgignore_link = os.path.expanduser('~/.hgignore')
    mklink(hgignore_file, hgignore_link)

@task('install-git')
def git():
    """Install git dot files"""
    git_dir =  os.path.join(ROOT, 'git')
    gitconfig_file = os.path.join(git_dir, 'gitconfig')
    gitconfig_link = os.path.expanduser('~/.gitconfig')
    mklink(gitconfig_file, gitconfig_link)

    gitignore_file = os.path.join(git_dir, 'gitignore')
    gitignore_link = os.path.expanduser('~/.gitignore')
    mklink(gitignore_file, gitignore_link)

@task('install-ipython')
def ipython():
    """Install IPython dot files"""
    ipython_dir =  os.path.join(ROOT, 'ipython')
    ipython_link = os.path.expanduser('~/.ipython')
    mklink(ipython_dir, ipython_link)

@task('install-sublime-text-2')
def sublime(sublime_settings_dir='~/Library/Application Support/Sublime Text 2/Packages/User'):
    """Install Sublime settings"""
    install_location = os.path.expanduser(sublime_settings_dir)
    sublime_settings = os.path.join(ROOT, 'sublime_text_2', 'settings')
    for filepath in glob.glob(os.path.join(sublime_settings, '*.sublime-*')):
        filename = os.path.basename(filepath)
        file_link = os.path.join(install_location, filename)
        if os.path.exists(file_link):
            os.unlink(file_link)
        mklink(filepath, file_link)

@task('install-all')
def all():
    """Install Emacs, Bash, Tcsh, Mercurial, git, IPython dot files"""
    emacs()
    bash()
    tcsh()
    hg()
    git()
    ipython()
    sublime()

if __name__ == '__main__':
    all()
